#!/bin/sh

[ -z "$1" ] && echo "Give either a pdf file or a DOI as an argument." && exit

if [ -f "$1" ]; then
	# Try to get DOI from pdfinfo or pdftotext output.
	doi="$(pdfinfo "$1" | grep -io "doi:.*")" ||
	doi="$(pdftotext "$1" 2>/dev/null - | grep -io "doi:.*" -m 1)" ||
	arxiv="$(pdfinfo "$1" | grep -io "arxiv:.*")" ||
	arxiv="$(pdftotext "$1" 2>/dev/null - | grep -io "arxiv:.*" -m 1)" || exit 1
	# echo "no identifier found" && exit 1
	echo "$arxiv"
fi
# echo "Before 2. condition"
if [ -z ${doi+x} ]; then
	echo "doi is found"
	doi_nospace="$(echo "$doi" | sed "s/ //g")" 
	echo "$doi_nospace"
       	curl -s "http://api.crossref.org/works/$doi_nospace/transform/application/x-bibtex" -w "\\n" || exit 1
elif [ -z ${arxiv+x} ]; then
	echo "arxiv is found"
	arxiv_nospace="$(echo "$arxiv" | sed "s/ //g")" ||
	echo "$arxiv_nospace"
	arxivtobibtex.py "$arxiv_nospace" || exit 1
fi
# echo "after 2. condition"


# "([aA]r[xX]iv\:.*?)\ "
# [ -z ${var+x} ]
# Check crossref.org for the bib citation.
