#!/bin/bash
[ "$1" = "" -o "$2" = "" ] && echo "give regex arg. and folder to crawl and rename its files" && exit
[ -z "$2" ] && echo "Give directory containing references to be added to bibliography" && exit

if [ -d "$2" ]; then
	echo "$(crawl "$2" | grep ".*\.pdf" -)" | while read line; do
		rename "$1" "$line" || exit 1
	done
fi
